export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const PUT_TOGGLE_WISHLIST_REQUEST = 'PUT_TOGGLE_WISHLIST_REQUEST';
export const PUT_TOGGLE_WISHLIST_SUCCESS = 'PUT_TOGGLE_WISHLIST_SUCCESS';
export const PUT_TOGGLE_WISHLIST_ERROR = 'PUT_TOGGLE_WISHLIST_ERROR';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

export const NO_PRODUCTS_MESSAGE = 'No products to show...';
