export const CHECK_AUTH_STATUS_REQUEST = 'CHECK_AUTH_STATUS_REQUEST';
export const CHECK_AUTH_STATUS_SUCCESS = 'CHECK_AUTH_STATUS_SUCCESS';
export const CHECK_AUTH_STATUS_ERROR = 'CHECK_AUTH_STATUS_ERROR';

export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SHOW_ERROR = 'SHOW_ERROR';

export const GET_SESSION_REQUEST = 'GET_SESSION_REQUEST';
export const GET_SESSION_SUCCESS = 'GET_SESSION_SUCCESS';

export const GET_INIT_REQUEST = 'GET_INIT_REQUEST';
export const GET_INIT_SUCCESS = 'GET_INIT_SUCCESS';
export const GET_INIT_ERROR = 'GET_INIT_ERROR';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL';
export const HIDE_AUTH_MODAL = 'HIDE_AUTH_MODAL';

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const POST_SIGN_UP_REQUEST = 'POST_SIGN_UP_REQUEST';
export const POST_SIGN_UP_SUCCESS = 'POST_SIGN_UP_SUCCESS';
export const POST_SIGN_UP_ERROR = 'POST_SIGN_UP_ERROR';
